{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastmcp-calculator
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "api.macdonml.com"
      http:
        paths:
          - path: "/calculator"
            pathType: Prefix
            backend:
              service:
                name: fastmcp-calculator
                port:
                  number: {{ .Values.service.port }}
{{- end }}
