apiVersion: v1
kind: Service
metadata:
  name: fastmcp-calculator
  labels:
    app: fastmcp-calculator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: fastmcp-calculator
